name: 功能请求
description: 为该项目提出新功能建议
title: "[Feature] 功能名称（请填写具体名称，如 '[Feature] 支持双击卡'）"
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: 验证步骤（必填）
      description: 请仔细阅读以下内容并勾选确认，否则该 Issue 可能被关闭。
      options:
        - label: 我已阅读并理解 [README](https://github.com/TonyJiangWJ/Ant-Forest/blob/master/README.md)，并且运行了 `可视化配置.js` 理解了其中的菜单项。确认该功能未被实现。
          required: true
        - label: 我已搜索现有 [Issues](https://github.com/TonyJiangWJ/Ant-Forest/issues?q=is%3Aissue)，确认没有类似功能请求。
          required: true
        - label: 功能疑问请移步 [Discussions](https://github.com/TonyJiangWJ/Ant-Forest/discussions) 或者 [论坛](https://autoscripts.flarum.cloud/)。
          required: false
  - type: input
    id: feature-name
    attributes:
      label: 功能名称
      description: 请用简短的名称描述该功能（例如：支持双击卡）。
      placeholder: 例如：支持双击卡
    validations:
      required: true
  - type: textarea
    attributes:
      label: 功能描述（必填）
      description: 请详细描述该功能的用途、使用场景和预期效果。避免模糊表述。
      placeholder: |
        - **使用场景**：在什么情况下需要此功能？
        - **预期效果**：该功能应实现什么具体行为？
        - **附加说明**：是否有技术实现建议或优先级说明？
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 功能优先级（选填）
      description: 请根据您的需求选择优先级（非必填，但有助于评估）。
      options:
        - 低
        - 中
        - 高
  - type: textarea
    attributes:
      label: 附加信息（选填）
      description: 其他相关信息（如技术实现建议、使用案例等）。