name: Bug 报告
description: "提交一个可复现的 Bug"
title: "[Bug] 问题简要描述"
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 验证步骤
      description: 在提交之前，请勾选以下选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      options:
        - label: 我已提供清晰的问题描述以及复现步骤和日志。
          required: true
        - label: 我已阅读并遵循了项目 [README](https://github.com/TonyJiangWJ/Ant-Forest/blob/master/README.md) 的指引，已经正确阅读常见问题中所描述的内容。
          required: true
        - label: 我已搜索现有 [Issues](https://github.com/TonyJiangWJ/Ant-Forest/issues?q=is%3Aissue)，确认没有重复问题。
          required: true
        - label: 功能疑问请移步 [Discussions](https://github.com/TonyJiangWJ/Ant-Forest/discussions) 或者 [论坛](https://autoscripts.flarum.cloud/)。
          required: false

  - type: textarea
    attributes:
      label: 描述
      description: 请提供错误的详细描述。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现方式
      description: 请提供重现错误的步骤
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 复现的预期结果
    validations:
      required: false
  - type: textarea
    attributes:
      label: 实际结果
      description: 实际的结果
    validations:
      required: false
  - type: textarea
    attributes:
      label: 日志/截图
      description: 在下方附上运行日志，或附上日志截图。脚本详细日志文件所在位置为 `logs/log-verboses.log`, 历史日志在`logs/logback`目录下。如运行报错请直接长截图AutoJS日志以便查看详细的报错信息
    validations:
      required: true